const IMG = "systems/parallax-protocol/assets/icons/armor.svg";

const items = [
    {
        name: "Light Ship Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 0,
            kineticDr: 0,
            energyDr: 1,
            dexPenalty: 0,
            speedPenalty: 0,
            saveBonuses: { radiation: 1, stun: 0 },
            notes: "",
        },
    },
    {
        name: "Light Ballistics Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 0,
            kineticDr: 1,
            energyDr: 0,
            dexPenalty: 0,
            speedPenalty: 0,
            saveBonuses: { radiation: 0, stun: 0 },
            notes: "",
        },
    },
    {
        name: "Light Extravehicular Activity Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 2,
            kineticDr: 1,
            energyDr: 2,
            dexPenalty: 1,
            speedPenalty: 5,
            saveBonuses: { radiation: 4, stun: 2 },
            notes: "<p>Includes helmet &amp; atmo-canister. Vacuum safe.</p>",
        },
    },
    {
        name: "Medium Ship Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 1,
            kineticDr: 1,
            energyDr: 1,
            dexPenalty: 0,
            speedPenalty: 0,
            saveBonuses: { radiation: 2, stun: 1 },
            notes: "",
        },
    },
    {
        name: "Medium Combat Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 2,
            kineticDr: 2,
            energyDr: 2,
            dexPenalty: 1,
            speedPenalty: 5,
            saveBonuses: { radiation: 2, stun: 2 },
            notes: "",
        },
    },
    {
        name: "Medium Extravehicular Activity Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 3,
            kineticDr: 2,
            energyDr: 3,
            dexPenalty: 2,
            speedPenalty: 10,
            saveBonuses: { radiation: 5, stun: 3 },
            notes: "<p>Includes helmet &amp; atmo-canister. Vacuum safe.</p>",
        },
    },
    {
        name: "Heavy Combat Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 3,
            kineticDr: 2,
            energyDr: 2,
            dexPenalty: 2,
            speedPenalty: 10,
            saveBonuses: { radiation: 3, stun: 3 },
            notes: "",
        },
    },
    {
        name: "Heavy Combat Shell",
        img: IMG,
        type: "armor",
        system: {
            bulk: 4,
            kineticDr: 3,
            energyDr: 3,
            dexPenalty: 3,
            speedPenalty: 15,
            saveBonuses: { radiation: 3, stun: 4 },
            notes: "<p>Includes helmet &amp; atmo-canister. Vacuum safe.</p>",
        },
    },
    {
        name: "Heavy Extravehicular Activity Suit",
        img: IMG,
        type: "armor",
        system: {
            bulk: 4,
            kineticDr: 3,
            energyDr: 4,
            dexPenalty: 3,
            speedPenalty: 15,
            saveBonuses: { radiation: 6, stun: 4 },
            notes: "<p>Includes helmet &amp; atmo-canister. Includes propulsive pack. Self-healing to reasonable punctures. Vacuum safe.</p>",
        },
    },
    {
        name: "Power Combat Armor",
        img: IMG,
        type: "armor",
        system: {
            bulk: 1,
            kineticDr: 5,
            energyDr: 5,
            dexPenalty: 4,
            speedPenalty: 5,
            saveBonuses: { radiation: 4, stun: 5 },
            notes: "<p>Includes helmet &amp; atmo-canister. Vacuum safe.</p>",
        },
    },
];

const folder = await Folder.create({ name: "Armor", type: "Item" });
const created = await Item.createDocuments(items.map(d => ({ ...d, folder: folder.id })));
ui.notifications.info(`Created ${created.length} armor items in folder "${folder.name}".`);
